### ISSUE TITLE
Errors under Minecraft 1.20

### ISSUE THREAD

**Issue by Eskuero** [mrgeneralq/sleep-most#176]
**Describe the bug**
Error logs on Minecraft 1.20

**To Reproduce**
Version 5.2.5 under stable release Paper 

```
[20:00:37 ERROR]: Could not pass event SleepSkipEvent to sleep-most v5.2.5
java.lang.NullPointerException: Cannot invoke "me.mrgeneralq.sleepmost.interfaces.IBossBarService.setVisible(org.bukkit.World, boolean)" because "this.bossBarService" is null
        at me.mrgeneralq.sleepmost.eventlisteners.SleepSkipEventListener.onSleepSkip(SleepSkipEventListener.java:105) ~[sleep-most-5.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor120.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:git-Paper-"3722877"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.jar:git-Paper-"3722877"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.jar:git-Paper-"3722877"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
        at me.mrgeneralq.sleepmost.services.SleepService.executeSleepReset(SleepService.java:291) ~[sleep-most-5.2.5.jar:?]
        at me.mrgeneralq.sleepmost.eventlisteners.PlayerSleepStateChangeEventListener.lambda$onPlayerSleepStateChange$1(PlayerSleepStateChangeEventListener.java:122) ~[sleep-most-5.2.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.jar:git-Paper-"3722877"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.20.jar:git-Paper-"3722877"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[paper-1.20.jar:git-Paper-"3722877"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.jar:git-Paper-"3722877"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.20.jar:git-Paper-"3722877"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.20.jar:git-Paper-"3722877"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-"3722877"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mrgeneralq** [comment]
Hello @Eskuero 

Thank you for the report and apologies for the delay. The fix is completed and should be released any moment.

Kind regards

Quinten

**Comment by Eskuero** [comment]
Updated the plugin from spigot site and the issue seems gone.
