### ISSUE TITLE
Critical: update check blocks the main thread

### ISSUE THREAD

**Issue by metzg** [mrgeneralq/sleep-most#35]
`UpdateRepository.getLatestVersion()` runs on or blocks the main thread, which causes the whole server to hang while the HTTP request is being processed. This can even lead to a complete crash if the request hangs indefinitely.

The update check needs to run asynchronously to avoid blocking the main thread, and a timeout should be specified to prevent this task from running indefinitely.

```
Bukkit.getScheduler().runTaskAsynchronously(pluginInstance, () -> {
        // ...update code, http request but with a timeout...
});
```

Also, the result of the API call should be cached for at least a few hours, as it is unlikely to change that often, and making too many requests adds unnecessary load (and in that case, makes the server even more vulnerable to the endpoint being down/slow).

In order to avoid other updater-related issues in the future, it would be nice to be able to disable update checks in `config.yml`.

**Comment by metzg** [comment]
```
[13:35:43] [Paper Watchdog Thread/ERROR]: ------------------------------
[13:35:43] [Paper Watchdog Thread/ERROR]: Current Thread: Thread-175
[13:35:43] [Paper Watchdog Thread/ERROR]: 	PID: 737 | Suspended: false | Native: true | State: RUNNABLE
[13:35:43] [Paper Watchdog Thread/ERROR]: 	Thread is waiting on monitor(s):
[13:35:43] [Paper Watchdog Thread/ERROR]: 		Locked on:java.base@11.0.8/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		Locked on:java.base@11.0.8/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		Locked on:java.base@11.0.8/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		Locked on:java.base@11.0.8/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		Locked on:java.base@11.0.8/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[13:35:43] [Paper Watchdog Thread/ERROR]: 	Stack:
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/java.net.PlainSocketImpl.socketConnect(Native Method)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/java.net.Socket.connect(Socket.java:609)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/java.net.URL.openStream(URL.java:1140)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		me.qintinator.sleepmost.repositories.UpdateRepository.getLatestVersion(UpdateRepository.java:18)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		me.qintinator.sleepmost.services.UpdateService.hasUpdate(UpdateService.java:23)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		me.qintinator.sleepmost.eventlisteners.OnPlayerJoin.lambda$onPlayerJoin$0(OnPlayerJoin.java:29)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		me.qintinator.sleepmost.eventlisteners.OnPlayerJoin$$Lambda$5662/0x000000084156ac40.run(Unknown Source)
[13:35:43] [Paper Watchdog Thread/ERROR]: 		java.base@11.0.8/java.lang.Thread.run(Thread.java:834)
[13:35:43] [Paper Watchdog Thread/ERROR]: ------------------------------
[13:35:44] [Paper Watchdog Thread/INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[13:36:50] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to sleep-most v4.3.0
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:942) [?:?]
	at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:763) ~[patched_1.16.1.jar:git-Paper-130]
	at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-130]
	at net.minecraft.server.v1_16_R1.MinecraftServer.close(MinecraftServer.java:737) ~[patched_1.16.1.jar:git-Paper-130]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.16.1.jar:git-Paper-130]

```

**Comment by mrgeneralq** [comment]
Hello @metzg 

All of it, valid points. We figured out the root cause and are currently working on a fix.
